  image: node:v18.17.1
  cache:
     paths:
       - node_modules/ 

  deploy prod:
    stage: deploy
    script:
    # Установка зависимостей
    -   npm install
    # Установка firebase-tools
    -   npm i -g firebase-tools
    # Сборка приложения
    -   npm run build


