stages:
  - build
  - deploy

variables:
  FIREBASE_PROJECT_ID: "dpmfb-3b66c"

build site:
  image: node:alpine  
  stage: build
  script:
    - npm install --progress=false
    - npm install -g @vue/cli
    - cd project
    - npm install @vue/cli-service
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - project/dist


deploy_firebase:
  image: node:alpine
  stage: deploy
  script:
    - npm install -g firebase-tools
    - cd project
    - head -c -2 firebase.json > temp_file.txt && mv temp_file.txt firebase.json
    - echo "$GOOGLE_APPLICATION_CREDENTIALS" >> firebase.json 
    - cat firebase.json
    - firebase deploy --only hosting
  #   - master
