stages:
  - build

variables:
  NODE_VERSION: "14"

before_script:  

  - apt-get update -qy
  - apt-get install -y curl
  - curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash -
  - apt-get install -y nodejs
  - node --version
  - npm --version
  - npm install -g @vue/cli

build:
  stage: build
  script:
    - npm install
    - npm run build

