stages:
  - build
  - deploy

variables:
  FIREBASE_PROJECT_ID: "dpmfb-3b66c"

build site:
  image: node:alpine  
  stage: build
  script:
    - npm install --progress=false
    - npm install -g @vue/cli
    - cd project
    - npm install @vue/cli-service
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - project/dist


deploy_firebase:
  image: node:alpine
  stage: deploy
  script:
    - npm install -g firebase-tools
    - cd project
    - firebase use $FIREBASE_PROJECT_ID
    - firebase deploy --only hosting --token "1//09pAxDnLmmGW8CgYIARAAGAkSNwF-L9Ir4tEEupP6idgY6IIczF8kIvfZOa0qUugBO4M_yr4UODJ6DoyUtVETbQ0gv995-0WeP54"
  # only:
  #   - master
