stages:
  - build
  - deploy

variables:
  FIREBASE_PROJECT_ID: "dpmfb-3b66c"

build site:

  image: node:latest
  
  stage: build
  script:
    - npm install --progress=false
    - npm install -g @vue/cli
    - cd project
    - npm install @vue/cli-service
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - project/dist

deploy_firebase:
  stage: deploy
  script:
    - npm install -g firebase-tools
    - firebase use $FIREBASE_PROJECT_ID
    - firebase deploy --only hosting
  only:
    - master
